---

- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Add certbot repository
  apt_repository:
   repo: 'ppa:certbot/certbot'

- name: Install certbot package dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  register: install_certbot_package_dependencies
  with_items: "{{ _certbot_package_dependencies | default([]) }}"
  when:
    - _certbot_package_dependencies is defined
  tags:
    - dependences
